name: C/C++ CI
  
on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - run: ./autogen.sh
    - run: ./configure
    - run: |
        make -j2
        sudo make install