name: Ubuntu 18.04

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu20:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        run: |
          sudo fallocate -l 6G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo apt-get update
          sudo apt-get upgrade
          #sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:bitcoin/bitcoin
          sudo apt-get install -y git libdb4.8-dev libdb4.8++-dev libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev libboost-program-options-dev
          build_folder="build/debug"
          xaya_version=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          xaya_ver_folder=$(echo $xaya_version | sed 's/\.//g')
          release_name=xaya-cli-ubuntu-2004-v"$xaya_version"
          ls -lh 
          mkdir -p "$build_folder"
          cd "$build_folder"
          #cmake ../..
          make -j2
          mkdir -p "$release_name/$xaya_ver_folder"
          exeFiles=()
          for f in src/*; do [[ -x $f && -f $f ]] && exeFiles+=( "$f" ); done
          cp "${exeFiles[@]}" "$release_name/$xaya_ver_folder"
          cd "$release_name"
          tar -czf "$release_name".tar.gz "$xaya_ver_folder"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name/$release_name.tar.gz"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=xaya_version::${xaya_version}"
      # since https://github.com/softprops/action-gh-release/pull/145 body is replaced instead of being appended
      # use v0.1.12 for now
      #- name: Create Release
      #  uses: softprops/action-gh-release@v0.1.12
      #  with:
      #    files: ${{ steps.build.outputs.asset_path }}
      #    name: Xaya CLI v${{ steps.build.outputs.xaya_version }}
      #    body: |
      #      [Download for Ubuntu 20.04](../../releases/download/${{ steps.build.outputs.xaya_version }}/${{ steps.build.outputs.release_name }}) **${{ steps.build.outputs.release_name }}**
      #     `SHA256 : ${{ steps.build.outputs.sha256 }}`
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
